services:

  minio:
    image: minio/minio
    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    command: server /data --console-address ":9001"

    volumes:
      - ./storage/data_lake:/data


  graphdb:
    image: ontotext/graphdb:11.3.0
    container_name: graphdb

    ports:
      - "7200:7200"

    volumes:
      - ./storage/graphdb:/opt/graphdb/home

